# Change these first
owner: TwoThreeWang # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: 搜索引擎
    url: https://error.work
  - name: 电影搜索
    url: https://v.error.work
  - name: 博客
    url: https://blog.error.work
  - name: 公共API
    url: https://api.error.work
  - name: wiki
    url: https://wiki.error.work
  - name: chat
    url: https://chat.error.work
  - name: talk
    url: https://talk.error.work
  - name: Tools
    url: https://tool.error.work
  - name: CDN
    url: https://cdn.error.work

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 膨胀的网站状态监控
  introTitle: "自动化监控膨胀系列网站可用性状态。"
  introMessage: 以下是目前各站点最新的存活状态
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
